import { StoreData } from "@/types/store";
import { Product } from "@/types/product";
import { Category } from "@/types/category";

export const DEMO_STORE_CATEGORIES: Category[] = [
  {
    id: "cat-decor",
    name: "Home Decor",
    slug: "home-decor",
    description: "Artisanal decorative accents for modern living spaces",
    status: "published",
    displayOrder: 1,
    productCount: 1,
    createdAt: "2026-02-01T10:00:00Z",
    updatedAt: "2026-02-01T10:00:00Z",
  },
  {
    id: "cat-leather",
    name: "Leather Goods",
    slug: "leather-goods",
    description: "Full-grain handcrafted leather accessories",
    status: "published",
    displayOrder: 2,
    productCount: 1,
    createdAt: "2026-02-01T10:00:00Z",
    updatedAt: "2026-02-01T10:00:00Z",
  },
  {
    id: "cat-fragrance",
    name: "Home Fragrance",
    slug: "home-fragrance",
    description: "Hand-poured pure botanical soy candles and diffusers",
    status: "published",
    displayOrder: 3,
    productCount: 1,
    createdAt: "2026-02-01T10:00:00Z",
    updatedAt: "2026-02-01T10:00:00Z",
  },
  {
    id: "cat-textiles",
    name: "Textiles",
    slug: "textiles",
    description: "Organic pre-washed European flax linens",
    status: "published",
    displayOrder: 4,
    productCount: 1,
    createdAt: "2026-02-01T10:00:00Z",
    updatedAt: "2026-02-01T10:00:00Z",
  },
  {
    id: "cat-kitchen",
    name: "Kitchenware",
    slug: "kitchenware",
    description: "Hand-carved sustainable wooden tableware",
    status: "published",
    displayOrder: 5,
    productCount: 1,
    createdAt: "2026-02-01T10:00:00Z",
    updatedAt: "2026-02-01T10:00:00Z",
  },
  {
    id: "cat-lighting",
    name: "Lighting",
    slug: "lighting",
    description: "Solid brass minimalist lamps and illumination",
    status: "published",
    displayOrder: 6,
    productCount: 1,
    createdAt: "2026-02-01T10:00:00Z",
    updatedAt: "2026-02-01T10:00:00Z",
  },
];

export const DEMO_STORE_PRODUCTS: Product[] = [
  {
    id: "prod-ceramic-vase",
    name: "Artisanal Hand-Thrown Ceramic Vase",
    slug: "artisanal-ceramic-vase",
    shortDescription: "Handcrafted stoneware vase featuring an organic textured matte glaze.",
    longDescription: "Handcrafted stoneware vase featuring an organic textured matte glaze. Perfect for dried florals, eucalyptus branches, or as a standalone sculptural accent on open shelves and coffee tables.",
    price: 2499,
    compareAtPrice: 3200,
    images: [
      { id: "img-v1", url: "https://images.unsplash.com/photo-1612196808214-b8e1d6145a8c?w=1000", isCover: true, position: 0 },
      { id: "img-v2", url: "https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?w=1000", isCover: false, position: 1 },
    ],
    categoryId: "cat-decor",
    categoryName: "Home Decor",
    stock: 14,
    featured: true,
    sku: "CSC-VASE-01",
    tags: ["handmade", "ceramics", "decor", "artisan"],
    status: "published",
    seoTitle: "Artisanal Ceramic Vase | Kraftaura Classic",
    seoDescription: "Hand-thrown stoneware ceramic vase with minimalist natural matte finish.",
    views: 128,
    createdAt: "2026-02-01T10:00:00Z",
    updatedAt: "2026-02-01T10:00:00Z",
  },
  {
    id: "prod-leather-tote",
    name: "Minimalist Vegetable-Tanned Leather Tote",
    slug: "minimalist-leather-tote",
    shortDescription: "Full-grain artisanal leather tote with solid brass hardware.",
    longDescription: "Crafted from full-grain vegetable-tanned leather that develops a rich patina over time. Features solid brass hardware, reinforced hand-stitched handles, and a dedicated internal slip pocket.",
    price: 4899,
    compareAtPrice: 5999,
    images: [
      { id: "img-l1", url: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=1000", isCover: true, position: 0 },
      { id: "img-l2", url: "https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=1000", isCover: false, position: 1 },
    ],
    categoryId: "cat-leather",
    categoryName: "Leather Goods",
    stock: 8,
    featured: true,
    sku: "CSC-TOTE-02",
    tags: ["leather", "accessories", "tote", "handcrafted"],
    status: "published",
    seoTitle: "Minimalist Leather Tote | Kraftaura Classic",
    seoDescription: "Handcrafted full-grain vegetable tanned leather tote bag.",
    views: 94,
    createdAt: "2026-02-02T11:30:00Z",
    updatedAt: "2026-02-02T11:30:00Z",
  },
  {
    id: "prod-soy-candle",
    name: "Hand-Poured Amber & Oak Soy Candle",
    slug: "amber-oak-soy-candle",
    shortDescription: "Pure soy wax candle with botanical essential oils in amber glass.",
    longDescription: "100% natural soy wax hand-poured into an amber glass jar. Infused with pure essential oils of smoky cedarwood, warm amber, and golden vanilla bean. Features an unbleached organic cotton wick for a 50-hour clean burn.",
    price: 899,
    compareAtPrice: 1199,
    images: [
      { id: "img-c1", url: "https://images.unsplash.com/photo-1603006905003-be475563bc59?w=1000", isCover: true, position: 0 },
      { id: "img-c2", url: "https://images.unsplash.com/photo-1572726729437-370d6d60c6d7?w=1000", isCover: false, position: 1 },
    ],
    categoryId: "cat-fragrance",
    categoryName: "Home Fragrance",
    stock: 25,
    featured: true,
    sku: "CSC-CNDL-03",
    tags: ["candle", "aromatherapy", "soy-wax", "organic"],
    status: "published",
    seoTitle: "Amber & Oak Soy Candle | Kraftaura Classic",
    seoDescription: "Botanical hand-poured natural soy wax candle in amber glass.",
    views: 215,
    createdAt: "2026-02-03T09:15:00Z",
    updatedAt: "2026-02-03T09:15:00Z",
  },
  {
    id: "prod-linen-runner",
    name: "Organic French Linen Table Runner",
    slug: "french-linen-table-runner",
    shortDescription: "Pre-washed pure European flax linen runner with frayed edges.",
    longDescription: "Woven from 100% pure European flax linen, pre-washed for effortless softness and relaxed natural texture. Finished with hand-frayed edges for timeless, understated dining elegance.",
    price: 1699,
    compareAtPrice: 2199,
    images: [
      { id: "img-r1", url: "https://images.unsplash.com/photo-1595475207225-428b62bda831?w=1000", isCover: true, position: 0 },
      { id: "img-r2", url: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=1000", isCover: false, position: 1 },
    ],
    categoryId: "cat-textiles",
    categoryName: "Textiles",
    stock: 18,
    featured: false,
    sku: "CSC-LINN-04",
    tags: ["linen", "dining", "tableware", "natural"],
    status: "published",
    seoTitle: "Organic French Linen Runner | Kraftaura Classic",
    seoDescription: "Pure French flax linen table runner with natural raw fringe.",
    views: 82,
    createdAt: "2026-02-04T14:20:00Z",
    updatedAt: "2026-02-04T14:20:00Z",
  },
  {
    id: "prod-teak-bowl",
    name: "Sculptural Teak Wood Serving Bowl",
    slug: "sculptural-teak-bowl",
    shortDescription: "Hand-turned sustainable teak bowl with food-safe beeswax finish.",
    longDescription: "Individually hand-turned from a single block of sustainably harvested plantation teak. Finished with organic food-safe mineral oil and beeswax, showcasing warm natural grain variations.",
    price: 2199,
    compareAtPrice: 2800,
    images: [
      { id: "img-b1", url: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=1000", isCover: true, position: 0 },
      { id: "img-b2", url: "https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?w=1000", isCover: false, position: 1 },
    ],
    categoryId: "cat-kitchen",
    categoryName: "Kitchenware",
    stock: 12,
    featured: true,
    sku: "CSC-TEAK-05",
    tags: ["woodwork", "kitchen", "bowl", "sustainable"],
    status: "published",
    seoTitle: "Sculptural Teak Wood Bowl | Kraftaura Classic",
    seoDescription: "Solid hand-turned plantation teak wood salad and fruit bowl.",
    views: 140,
    createdAt: "2026-02-05T16:45:00Z",
    updatedAt: "2026-02-05T16:45:00Z",
  },
  {
    id: "prod-brass-lamp",
    name: "Solid Brass Minimalist Desk Lamp",
    slug: "solid-brass-desk-lamp",
    shortDescription: "Brushed solid brass desk lamp with integrated touch dimmer.",
    longDescription: "Precision-machined from solid brushed brass. Features an adjustable directional hood, integrated touch dimmer switch, and a vintage-inspired braided olive fabric power cord.",
    price: 3799,
    compareAtPrice: 4500,
    images: [
      { id: "img-m1", url: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=1000", isCover: true, position: 0 },
      { id: "img-m2", url: "https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=1000", isCover: false, position: 1 },
    ],
    categoryId: "cat-lighting",
    categoryName: "Lighting",
    stock: 6,
    featured: true,
    sku: "CSC-LAMP-06",
    tags: ["lighting", "brass", "lamp", "minimalist"],
    status: "published",
    seoTitle: "Solid Brass Desk Lamp | Kraftaura Classic",
    seoDescription: "Modern brushed solid brass architectural task desk light.",
    views: 188,
    createdAt: "2026-02-06T12:00:00Z",
    updatedAt: "2026-02-06T12:00:00Z",
  },
];

export const DEMO_STORE_DATA: StoreData = {
  id: "demo-craft-classic-id",
  name: "Kraftaura Classic",
  slug: "demo",
  plan: "growth",
  appearance: {
    themeId: "bloom",
    branding: {
      name: "Kraftaura Classic",
      tagline: "Handcrafted Artisan Living & Modern Essentials",
      description: "A curated collection of small-batch artisan homeware, leather goods, and sustainable living essentials crafted by master artisans.",
      logoUrl: "",
      whatsapp: "+91 98765 43210",
      phone: "+91 98765 43210",
      email: "demo@kraftaura.in",
      address: "Artisan Quarter, Mumbai, MH",
      instagram: "@kraftauraclassic",
      facebook: "facebook.com/kraftauraclassic",
    },
    colors: {
      primary: "#18181B",
      secondary: "#F4F4F5",
      accent: "#800020",
      background: "#FFFFFF",
    },
    typography: {
      headingFont: "Plus Jakarta Sans",
      bodyFont: "Inter",
      animationStyle: "smooth",
    },
    homepageSections: [
      { id: "hero", title: "Hero Banner", enabled: true, order: 1 },
      { id: "categories", title: "Categories", enabled: true, order: 2 },
      { id: "featured_products", title: "Curated Products", enabled: true, order: 3 },
      { id: "testimonials", title: "Customer Reviews", enabled: true, order: 4 },
      { id: "footer", title: "Footer", enabled: true, order: 5 },
    ],
    seo: {
      seoTitle: "Kraftaura Classic — Live Demo Storefront",
      seoDescription: "Explore our curated catalog of handcrafted artisan home decor, leather goods, and sustainable essentials with instant WhatsApp checkout.",
      socialImageUrl: "https://images.unsplash.com/photo-1612196808214-b8e1d6145a8c?w=1200",
    },
    updatedAt: "2026-02-06T12:00:00Z",
  },
  categories: DEMO_STORE_CATEGORIES,
  collections: [],
  products: DEMO_STORE_PRODUCTS,
  shipping: {
    freeShippingEnabled: true,
    freeShippingThreshold: 0,
  },
};
