import { Theme } from "@/types/theme";

export const initialThemes: Theme[] = [
  {
    id: "bloom",
    name: "Kraftaura Classic",
    description: "Sleek, high-converting light e-commerce layout tailored for boutique storefronts, handcrafted artisan goods, and modern brands.",
    thumbnail: "https://images.unsplash.com/photo-1612196808214-b8e1d6145a8c?w=600",
    previewImages: [],
    version: "1.0.0",
    author: "Kraftaura",
    supportsDarkMode: false,
    supportsHero: true,
    supportsCollections: true,
    supportsTestimonials: true,
    supportsVideo: false,
    status: "active",
  },
  {
    id: "midnight",
    name: "Midnight",
    description: "A bold, dark-mode focused theme optimized for tech, gadgets, and premium streetwear.",
    thumbnail: "https://images.unsplash.com/photo-1550525811-e5869dd03032?w=600",
    previewImages: [],
    version: "1.0.0",
    author: "Kraftaura",
    supportsDarkMode: true,
    supportsHero: true,
    supportsCollections: true,
    supportsTestimonials: false,
    supportsVideo: true,
    status: "available",
  },
  {
    id: "luxury",
    name: "Luxury",
    description: "Focus purely on your products with this ultra-clean, whitespace-heavy design.",
    thumbnail: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=600",
    previewImages: [],
    version: "1.0.0",
    author: "Kraftaura",
    supportsDarkMode: false,
    supportsHero: true,
    supportsCollections: true,
    supportsTestimonials: true,
    supportsVideo: true,
    status: "available",
  },
  {
    id: "creative",
    name: "Creative",
    description: "Built for speed and high-volume sales. Ideal for dropshippers, fast fashion, and multi-category superstores.",
    thumbnail: "https://images.unsplash.com/photo-1483985988355-763728e1935b?w=600",
    previewImages: [],
    version: "1.0.0",
    author: "Kraftaura",
    supportsDarkMode: true,
    supportsHero: true,
    supportsCollections: true,
    supportsTestimonials: true,
    supportsVideo: false,
    status: "available",
  },
  {
    id: "modern",
    name: "Modern",
    description: "Earthy tones and organic layouts. Designed for handmade goods, organic skincare, and sustainable brands.",
    thumbnail: "https://images.unsplash.com/photo-1608248593842-8021c6a8585e?w=600",
    previewImages: [],
    version: "1.0.0",
    author: "Kraftaura",
    supportsDarkMode: false,
    supportsHero: true,
    supportsCollections: true,
    supportsTestimonials: true,
    supportsVideo: false,
    status: "available",
  }
];
